package ExceptionHandling;

public class ExceptionHandling1 {
    public static void main(String[] args) {
        int []numbers={1,2,3,4,5};
        System.out.println("My Array:"+numbers[0]);
//        try {
//            int a = 10;
//            int b = 0;
//            int div = a/b;
//            System.out.println("Division:"+div);
//            // try block throws the exception
//
//
//        }
//        catch(ArithmeticException e){
//            System.out.println("My error is :"+e);
//            // to solving and handling the error or debugging the exception
//        }
////        finally {
////                    // always executing
////            System.out.println("my error is solved....:");
////       }
    }
}
